FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf

RUN apk add --no-cache nginx

RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /run/nginx

CMD ["nginx", "-g", "daemon off;"]
